version: 2
executorType: docker
containerInfo:
  - image: node:6
  - image: mongo:latest
stages:
  build:
    workDir: /home/ubuntu/bemuse-scoreboard
    steps:
      - type: checkout
      - type: shell
        name: Install dependencies
        command: npm install
      - type: shell
        name: Test
        command: npm test
      - type: shell
        name: System tests
        command: ./node_modules/.bin/nyc npm run system-tests
      - type: shell
        name: codecov
        command: |
          npm install -g 'dtinth/codecov-node#cci2' && codecov
